ALTER TABLE "Product"
ADD COLUMN "stock" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "category" TEXT NOT NULL DEFAULT 'Camisetas',
ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Image" DROP CONSTRAINT IF EXISTS "Image_productId_fkey";

ALTER TABLE "Image"
ADD CONSTRAINT "Image_productId_fkey"
FOREIGN KEY ("productId") REFERENCES "Product"("id")
ON DELETE CASCADE ON UPDATE CASCADE;
